# Optimized for Python 3.12 and https://github.com/beotavalo/python-qa
default_language_version:
    python: python3.12
repos:
# Pre-commit utilities
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-merge-conflict
# Core Formatters/Linters (Ruff replaces black, isort, flake8, pyupgrade, etc.)
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # Latest stable
    hooks:
# Run the linter.
      - id: ruff
        args:
          [
          "--select", "E,F,N,B",     # E: pycodestyle (style), F: pyflakes (logical errors), N: pep8-naming, B: flake8-bugbear (common bugs)
          "--fix",                  # Auto-fix issues where possible
          "--show-fixes"            # Show which fixes are applied
         ]
# Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: local
    hooks:
      - id: wily
        name: wily
        entry: wily diff
        verbose: true
        language: python
        additional_dependencies: [wily]
# Security
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-lll", "--skip", "B101"]

# Static Typing
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]

# Documentation
#-   repo: https://github.com/asottile/blacken-docs
#    rev: v1.16.0
#    hooks:
#      - id: blacken-docs
#        additional_dependencies: [black==24.3.0]
